# Generated by Django 4.1.7 on 2023-05-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars', verbose_name='Аватар'),
        ),
    ]
